name: googledriveclone
description: Here in this project I try to clone google drive with help of Firebase and GetX state management.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  
  # stateManagement and navigations
  get: ^4.6.5


  # firebase 
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2 
  firebase_storage: ^11.2.2 
  cloud_firestore: ^4.8.0

  # for signIn 
  google_sign_in: ^6.1.3 

  # for pick a file 
  file_picker: ^5.2.6 # old version 

  #path 
  path_provider: ^2.0.15 
  permission_handler: ^10.2.0 

  #url 
  url_launcher: ^6.1.11 

  #audio
  audioplayers: ^4.1.0 

  #video
  video_player: ^2.6.1
  chewie: ^1.4.1 

  #download 
  flutter_downloader: ^1.10.4 
  


  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Thin.otf 
          weight: 100
        - asset: assets/fonts/Montserrat-ExtraLight.otf
          weight: 200
        - asset: assets/fonts/Montserrat-Light.otf
          weight: 300
        - asset: assets/fonts/Montserrat-Regular.otf
          weight: 400 
        - asset: assets/fonts/Montserrat-Medium.otf
          weight: 500
        - asset: assets/fonts/Montserrat-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Montserrat-Bold.otf
          weight: 700
        - asset: assets/fonts/Montserrat-ExtraBold.otf
          weight: 800
        - asset: assets/fonts/Montserrat-Black.otf
          weight: 900 
          



